language: python
python: # test various python versions, Django supports all of them
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.6-dev
env:
  matrix:
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11a1
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -q Django==$DJANGO_VERSION # install custom django version
  - pip install -r tests/user_foreign_key_testapp/requirements.txt
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.9 # Django 1.9 does not support python 3.3, but 3.4+
    - python: "3.3"
      env: DJANGO_VERSION=1.10 # Django 1.10 does not support python 3.3, but 3.4+
    - python: "3.3"
      env: DJANGO_VERSION=1.11a1
    - python: "nightly"
      env: DJANGO_VERSION=1.8 # Django 1.8 might not work with future versions of python
# Handle git submodules yourself (from http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci )
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
script:
  - cd tests/user_foreign_key_testapp/
  - python manage.py test # just need to run normal tests for now

