language: python
python: # test various python versions (Django Support for various python versions is described within the exclude: section)
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"  # PyPy2
  - "pypy3" # PyPy3
  - "nightly" # currently points to 3.7-dev
env:
  matrix:
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.8.* # latest 1.8
    - DJANGO_VERSION=1.11
    - DJANGO_VERSION=1.11.* # latest 1.11
    - DJANGO_VERSION=2.0
    - DJANGO_VERSION=2.0.* # latest 2.0
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -q Django==$DJANGO_VERSION # install custom django version
  - pip install -r tests/user_foreign_key_testapp/requirements.txt
matrix:
  exclude:
    # Django 2.0 does not support Python2.7/PyPy2 anymore
    - { python: "2.7", env: DJANGO_VERSION=2.0 }
    - { python: "pypy", env: DJANGO_VERSION=2.0 }
    - { python: "2.7", env: DJANGO_VERSION=2.0.* }
    - { python: "pypy", env: DJANGO_VERSION=2.0.* }
    # Django 1.8 might not support newer versions of python
    - { python: "3.6", env: DJANGO_VERSION=1.8 }
    - { python: "3.7", env: DJANGO_VERSION=1.8 }
    - { python: "pypy3", env: DJANGO_VERSION=1.8 }
    - { python: "nightly", env: DJANGO_VERSION=1.8 }
    - { python: "3.6", env: DJANGO_VERSION=1.8.* }
    - { python: "3.7", env: DJANGO_VERSION=1.8.* }
    - { python: "pypy3", env: DJANGO_VERSION=1.8.* }
    - { python: "nightly", env: DJANGO_VERSION=1.8.* }
  allow_failures:
    # newer python versions aswell as pypy may also always break our build
    - python: "3.7-dev"
    - python: "pypy"
    - python: "pypy3"
    - python: "nightly"
# Handle git submodules yourself (from http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci )
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
script:
  - cd tests/user_foreign_key_testapp/
  - python manage.py test # just need to run normal tests for now

