sudo: false
language: python
python: # test various python versions (Django Support for various python versions is described within the exclude: section)
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"  # PyPy2
  - "pypy3" # PyPy3
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  exclude:
    # Django >= 2.0 does not support Python2.7/PyPy2 anymore
    - { python: "2.7", env: DJANGO=2.0 }
    - { python: "pypy", env: DJANGO=2.0 }
    - { python: "2.7", env: DJANGO=2.1 }
    - { python: "pypy", env: DJANGO=2.1 }
    - { python: "2.7", env: DJANGO=master }
    - { python: "pypy", env: DJANGO=master }
    # Django >= 2.1 does not Support Python3.4 anymore
    - { python: "3.4", env: DJANGO=2.1 }
    - { python: "3.4", env: DJANGO=master }
  allow_failures:
    # newer python versions aswell as pypy may also always break our build
    - python: "pypy"
    - python: "pypy3"
    - env: DJANGO=master
# Handle git submodules yourself (from http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci )
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
install: pip install tox-travis
script: tox
