sudo: false
language: python
python: # test various python versions (Django Support for various python versions is described within the exclude: section)
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=master
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  exclude:
    - { python: "3.5", env: DJANGO=3.0 }
    - { python: "3.5", env: DJANGO=master }
  allow_failures:
    # newer python versions as well as pypy may also always break our build
    - python: "pypy3"
    - env: DJANGO=master
# Handle git submodules yourself (from http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci )
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
install: pip install tox-travis
script: tox
